import React from 'react';

const faqData = [
    {
        question: "What is the Product Viability Analyzer?",
        answer: "This tool is an AI-powered assistant designed for aspiring and current dropshippers. It analyzes a product idea you provide and generates a comprehensive report on its market viability, including competition, revenue potential, market saturation, and sourcing vendors."
    },
    {
        question: "How does the AI analysis work?",
        answer: "Our tool leverages a powerful generative AI model trained on vast amounts of e-commerce and market data. When you enter a product, it processes the request to identify market trends, find competitors, estimate financial potential, and synthesize this information into a clear, actionable report."
    },
    {
        question: "Is the data provided 100% accurate?",
        answer: "The analysis is generated by an AI and is based on publicly available data and trend analysis. While it's a powerful tool for research and decision-making, it should be used as a starting point. We always recommend conducting your own due diligence before making any financial commitments."
    },
    {
        question: "Can I use this for any type of product?",
        answer: "Yes, you can analyze virtually any physical product. The tool is optimized for the dropshipping model, so its analysis of vendors and competition will be most relevant for products suitable for that business model. The more specific your query, the better the results."
    }
];

const FaqItem: React.FC<{ q: string; a: string }> = ({ q, a }) => (
    <details className="group border-b border-base-300 py-4 last:border-b-0">
        <summary className="flex items-center justify-between font-semibold text-neutral-200 cursor-pointer list-none hover:text-brand-primary transition-colors">
            {q}
            <span className="transform transition-transform duration-300 group-open:rotate-45">
                 <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
            </span>
        </summary>
        <p className="text-neutral-400 mt-3">{a}</p>
    </details>
);


export const Faq: React.FC = () => {
    return (
        <section className="max-w-4xl mx-auto py-16" aria-labelledby="faq-title">
            <div className="text-center mb-10">
                <h2 id="faq-title" className="text-3xl font-bold text-neutral-100 mb-2">About & Frequently Asked Questions</h2>
                <p className="text-neutral-400 max-w-2xl mx-auto">
                   Learn more about how our AI-powered analysis can help you find your next winning product.
                </p>
            </div>
            
            <div className="bg-base-200 border border-base-300 rounded-xl p-6 md:p-8">
                {faqData.map((item, index) => (
                    <FaqItem key={index} q={item.question} a={item.answer} />
                ))}
            </div>
        </section>
    );
};